DROP TABLE `account_blob`;--> statement-breakpoint
DROP TABLE `account_message`;--> statement-breakpoint
DROP TABLE `account`;--> statement-breakpoint
DROP TABLE `address`;--> statement-breakpoint
DROP TABLE `attachment`;--> statement-breakpoint
DROP TABLE `auth_rate_limit`;--> statement-breakpoint
DROP TABLE `blob`;--> statement-breakpoint
DROP TABLE `change_log`;--> statement-breakpoint
DROP TABLE `email_keyword`;--> statement-breakpoint
DROP TABLE `email_submission`;--> statement-breakpoint
DROP TABLE `identity`;--> statement-breakpoint
DROP TABLE `jmap_query_state`;--> statement-breakpoint
DROP TABLE `jmap_state`;--> statement-breakpoint
DROP TABLE `mailbox_message`;--> statement-breakpoint
DROP TABLE `mailbox`;--> statement-breakpoint
DROP TABLE `message_address`;--> statement-breakpoint
DROP TABLE `message_header`;--> statement-breakpoint
DROP TABLE `message`;--> statement-breakpoint
DROP TABLE `oidc_auth_code`;--> statement-breakpoint
DROP TABLE `oidc_client`;--> statement-breakpoint
DROP TABLE `oidc_token`;--> statement-breakpoint
DROP TABLE `push_subscription`;--> statement-breakpoint
DROP TABLE `thread`;--> statement-breakpoint
DROP TABLE `vacation_response_log`;--> statement-breakpoint
DROP TABLE `vacation_response`;