/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAppIndexRouteImport } from './routes/_app/app/index'
import { Route as WebhookEmailMessageRecieverRouteImport } from './routes/webhook/email/message-reciever'
import { Route as ApiGraphqlSplatRouteImport } from './routes/api/graphql/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthAuthSignupRouteImport } from './routes/_auth/auth/signup'
import { Route as AuthAuthSigninRouteImport } from './routes/_auth/auth/signin'
import { Route as AppAppEmailRouteRouteImport } from './routes/_app/app/email/route'
import { Route as AppAppSettingsIndexRouteImport } from './routes/_app/app/settings/index'
import { Route as AppAppEmailIndexRouteImport } from './routes/_app/app/email/index'
import { Route as AppAppEmailThread_idRouteImport } from './routes/_app/app/email/$thread_id'
import { Route as AppAppEmailThread_idSenderSender_idRouteImport } from './routes/_app/app/email/$thread_id.sender.$sender_id'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AppRouteRoute,
} as any)
const WebhookEmailMessageRecieverRoute =
  WebhookEmailMessageRecieverRouteImport.update({
    id: '/webhook/email/message-reciever',
    path: '/webhook/email/message-reciever',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGraphqlSplatRoute = ApiGraphqlSplatRouteImport.update({
  id: '/api/graphql/$',
  path: '/api/graphql/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthSignupRoute = AuthAuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAuthSigninRoute = AuthAuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppAppEmailRouteRoute = AppAppEmailRouteRouteImport.update({
  id: '/app/email',
  path: '/app/email',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAppSettingsIndexRoute = AppAppSettingsIndexRouteImport.update({
  id: '/app/settings/',
  path: '/app/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAppEmailIndexRoute = AppAppEmailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppEmailRouteRoute,
} as any)
const AppAppEmailThread_idRoute = AppAppEmailThread_idRouteImport.update({
  id: '/$thread_id',
  path: '/$thread_id',
  getParentRoute: () => AppAppEmailRouteRoute,
} as any)
const AppAppEmailThread_idSenderSender_idRoute =
  AppAppEmailThread_idSenderSender_idRouteImport.update({
    id: '/sender/$sender_id',
    path: '/sender/$sender_id',
    getParentRoute: () => AppAppEmailThread_idRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/email': typeof AppAppEmailRouteRouteWithChildren
  '/auth/signin': typeof AuthAuthSigninRoute
  '/auth/signup': typeof AuthAuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/graphql/$': typeof ApiGraphqlSplatRoute
  '/webhook/email/message-reciever': typeof WebhookEmailMessageRecieverRoute
  '/app/': typeof AppAppIndexRoute
  '/app/email/$thread_id': typeof AppAppEmailThread_idRouteWithChildren
  '/app/email/': typeof AppAppEmailIndexRoute
  '/app/settings/': typeof AppAppSettingsIndexRoute
  '/app/email/$thread_id/sender/$sender_id': typeof AppAppEmailThread_idSenderSender_idRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/signin': typeof AuthAuthSigninRoute
  '/auth/signup': typeof AuthAuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/graphql/$': typeof ApiGraphqlSplatRoute
  '/webhook/email/message-reciever': typeof WebhookEmailMessageRecieverRoute
  '/app': typeof AppAppIndexRoute
  '/app/email/$thread_id': typeof AppAppEmailThread_idRouteWithChildren
  '/app/email': typeof AppAppEmailIndexRoute
  '/app/settings': typeof AppAppSettingsIndexRoute
  '/app/email/$thread_id/sender/$sender_id': typeof AppAppEmailThread_idSenderSender_idRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/app/email': typeof AppAppEmailRouteRouteWithChildren
  '/_auth/auth/signin': typeof AuthAuthSigninRoute
  '/_auth/auth/signup': typeof AuthAuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/graphql/$': typeof ApiGraphqlSplatRoute
  '/webhook/email/message-reciever': typeof WebhookEmailMessageRecieverRoute
  '/_app/app/': typeof AppAppIndexRoute
  '/_app/app/email/$thread_id': typeof AppAppEmailThread_idRouteWithChildren
  '/_app/app/email/': typeof AppAppEmailIndexRoute
  '/_app/app/settings/': typeof AppAppSettingsIndexRoute
  '/_app/app/email/$thread_id/sender/$sender_id': typeof AppAppEmailThread_idSenderSender_idRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/email'
    | '/auth/signin'
    | '/auth/signup'
    | '/api/auth/$'
    | '/api/graphql/$'
    | '/webhook/email/message-reciever'
    | '/app/'
    | '/app/email/$thread_id'
    | '/app/email/'
    | '/app/settings/'
    | '/app/email/$thread_id/sender/$sender_id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/signin'
    | '/auth/signup'
    | '/api/auth/$'
    | '/api/graphql/$'
    | '/webhook/email/message-reciever'
    | '/app'
    | '/app/email/$thread_id'
    | '/app/email'
    | '/app/settings'
    | '/app/email/$thread_id/sender/$sender_id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/app/email'
    | '/_auth/auth/signin'
    | '/_auth/auth/signup'
    | '/api/auth/$'
    | '/api/graphql/$'
    | '/webhook/email/message-reciever'
    | '/_app/app/'
    | '/_app/app/email/$thread_id'
    | '/_app/app/email/'
    | '/_app/app/settings/'
    | '/_app/app/email/$thread_id/sender/$sender_id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGraphqlSplatRoute: typeof ApiGraphqlSplatRoute
  WebhookEmailMessageRecieverRoute: typeof WebhookEmailMessageRecieverRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app/': {
      id: '/_app/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/webhook/email/message-reciever': {
      id: '/webhook/email/message-reciever'
      path: '/webhook/email/message-reciever'
      fullPath: '/webhook/email/message-reciever'
      preLoaderRoute: typeof WebhookEmailMessageRecieverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graphql/$': {
      id: '/api/graphql/$'
      path: '/api/graphql/$'
      fullPath: '/api/graphql/$'
      preLoaderRoute: typeof ApiGraphqlSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/auth/signup': {
      id: '/_auth/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthAuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/auth/signin': {
      id: '/_auth/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthAuthSigninRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/app/email': {
      id: '/_app/app/email'
      path: '/app/email'
      fullPath: '/app/email'
      preLoaderRoute: typeof AppAppEmailRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/app/settings/': {
      id: '/_app/app/settings/'
      path: '/app/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppAppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/app/email/': {
      id: '/_app/app/email/'
      path: '/'
      fullPath: '/app/email/'
      preLoaderRoute: typeof AppAppEmailIndexRouteImport
      parentRoute: typeof AppAppEmailRouteRoute
    }
    '/_app/app/email/$thread_id': {
      id: '/_app/app/email/$thread_id'
      path: '/$thread_id'
      fullPath: '/app/email/$thread_id'
      preLoaderRoute: typeof AppAppEmailThread_idRouteImport
      parentRoute: typeof AppAppEmailRouteRoute
    }
    '/_app/app/email/$thread_id/sender/$sender_id': {
      id: '/_app/app/email/$thread_id/sender/$sender_id'
      path: '/sender/$sender_id'
      fullPath: '/app/email/$thread_id/sender/$sender_id'
      preLoaderRoute: typeof AppAppEmailThread_idSenderSender_idRouteImport
      parentRoute: typeof AppAppEmailThread_idRoute
    }
  }
}

interface AppAppEmailThread_idRouteChildren {
  AppAppEmailThread_idSenderSender_idRoute: typeof AppAppEmailThread_idSenderSender_idRoute
}

const AppAppEmailThread_idRouteChildren: AppAppEmailThread_idRouteChildren = {
  AppAppEmailThread_idSenderSender_idRoute:
    AppAppEmailThread_idSenderSender_idRoute,
}

const AppAppEmailThread_idRouteWithChildren =
  AppAppEmailThread_idRoute._addFileChildren(AppAppEmailThread_idRouteChildren)

interface AppAppEmailRouteRouteChildren {
  AppAppEmailThread_idRoute: typeof AppAppEmailThread_idRouteWithChildren
  AppAppEmailIndexRoute: typeof AppAppEmailIndexRoute
}

const AppAppEmailRouteRouteChildren: AppAppEmailRouteRouteChildren = {
  AppAppEmailThread_idRoute: AppAppEmailThread_idRouteWithChildren,
  AppAppEmailIndexRoute: AppAppEmailIndexRoute,
}

const AppAppEmailRouteRouteWithChildren =
  AppAppEmailRouteRoute._addFileChildren(AppAppEmailRouteRouteChildren)

interface AppRouteRouteChildren {
  AppAppEmailRouteRoute: typeof AppAppEmailRouteRouteWithChildren
  AppAppIndexRoute: typeof AppAppIndexRoute
  AppAppSettingsIndexRoute: typeof AppAppSettingsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAppEmailRouteRoute: AppAppEmailRouteRouteWithChildren,
  AppAppIndexRoute: AppAppIndexRoute,
  AppAppSettingsIndexRoute: AppAppSettingsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAuthSigninRoute: typeof AuthAuthSigninRoute
  AuthAuthSignupRoute: typeof AuthAuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAuthSigninRoute: AuthAuthSigninRoute,
  AuthAuthSignupRoute: AuthAuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGraphqlSplatRoute: ApiGraphqlSplatRoute,
  WebhookEmailMessageRecieverRoute: WebhookEmailMessageRecieverRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
