/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAppIndexRouteImport } from './routes/_app/app/index'
import { Route as WebhookEmailMessageSentRouteImport } from './routes/webhook/email/message-sent'
import { Route as WebhookEmailMessageLoadedRouteImport } from './routes/webhook/email/message-loaded'
import { Route as WebhookEmailMessageLinkClickedRouteImport } from './routes/webhook/email/message-link-clicked'
import { Route as WebhookEmailMessageHeldRouteImport } from './routes/webhook/email/message-held'
import { Route as WebhookEmailMessageDeliveryFailedRouteImport } from './routes/webhook/email/message-delivery-failed'
import { Route as WebhookEmailMessageDelayedRouteImport } from './routes/webhook/email/message-delayed'
import { Route as WebhookEmailMessageBouncedRouteImport } from './routes/webhook/email/message-bounced'
import { Route as WebhookEmailDomainDnsErrorRouteImport } from './routes/webhook/email/domain-dns-error'
import { Route as ApiGraphqlSplatRouteImport } from './routes/api/graphql/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthAuthSignupRouteImport } from './routes/_auth/auth/signup'
import { Route as AuthAuthSigninRouteImport } from './routes/_auth/auth/signin'
import { Route as AppAppEmailRouteRouteImport } from './routes/_app/app/email/route'
import { Route as AppAppSettingsIndexRouteImport } from './routes/_app/app/settings/index'
import { Route as AppAppEmailIndexRouteImport } from './routes/_app/app/email/index'
import { Route as AppAppEmailThread_idRouteImport } from './routes/_app/app/email/$thread_id'
import { Route as AppAppEmailThread_idSenderSender_idRouteImport } from './routes/_app/app/email/$thread_id.sender.$sender_id'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AppRouteRoute,
} as any)
const WebhookEmailMessageSentRoute = WebhookEmailMessageSentRouteImport.update({
  id: '/webhook/email/message-sent',
  path: '/webhook/email/message-sent',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhookEmailMessageLoadedRoute =
  WebhookEmailMessageLoadedRouteImport.update({
    id: '/webhook/email/message-loaded',
    path: '/webhook/email/message-loaded',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebhookEmailMessageLinkClickedRoute =
  WebhookEmailMessageLinkClickedRouteImport.update({
    id: '/webhook/email/message-link-clicked',
    path: '/webhook/email/message-link-clicked',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebhookEmailMessageHeldRoute = WebhookEmailMessageHeldRouteImport.update({
  id: '/webhook/email/message-held',
  path: '/webhook/email/message-held',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhookEmailMessageDeliveryFailedRoute =
  WebhookEmailMessageDeliveryFailedRouteImport.update({
    id: '/webhook/email/message-delivery-failed',
    path: '/webhook/email/message-delivery-failed',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebhookEmailMessageDelayedRoute =
  WebhookEmailMessageDelayedRouteImport.update({
    id: '/webhook/email/message-delayed',
    path: '/webhook/email/message-delayed',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebhookEmailMessageBouncedRoute =
  WebhookEmailMessageBouncedRouteImport.update({
    id: '/webhook/email/message-bounced',
    path: '/webhook/email/message-bounced',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebhookEmailDomainDnsErrorRoute =
  WebhookEmailDomainDnsErrorRouteImport.update({
    id: '/webhook/email/domain-dns-error',
    path: '/webhook/email/domain-dns-error',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGraphqlSplatRoute = ApiGraphqlSplatRouteImport.update({
  id: '/api/graphql/$',
  path: '/api/graphql/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthSignupRoute = AuthAuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAuthSigninRoute = AuthAuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppAppEmailRouteRoute = AppAppEmailRouteRouteImport.update({
  id: '/app/email',
  path: '/app/email',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAppSettingsIndexRoute = AppAppSettingsIndexRouteImport.update({
  id: '/app/settings/',
  path: '/app/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAppEmailIndexRoute = AppAppEmailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppEmailRouteRoute,
} as any)
const AppAppEmailThread_idRoute = AppAppEmailThread_idRouteImport.update({
  id: '/$thread_id',
  path: '/$thread_id',
  getParentRoute: () => AppAppEmailRouteRoute,
} as any)
const AppAppEmailThread_idSenderSender_idRoute =
  AppAppEmailThread_idSenderSender_idRouteImport.update({
    id: '/sender/$sender_id',
    path: '/sender/$sender_id',
    getParentRoute: () => AppAppEmailThread_idRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/email': typeof AppAppEmailRouteRouteWithChildren
  '/auth/signin': typeof AuthAuthSigninRoute
  '/auth/signup': typeof AuthAuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/graphql/$': typeof ApiGraphqlSplatRoute
  '/webhook/email/domain-dns-error': typeof WebhookEmailDomainDnsErrorRoute
  '/webhook/email/message-bounced': typeof WebhookEmailMessageBouncedRoute
  '/webhook/email/message-delayed': typeof WebhookEmailMessageDelayedRoute
  '/webhook/email/message-delivery-failed': typeof WebhookEmailMessageDeliveryFailedRoute
  '/webhook/email/message-held': typeof WebhookEmailMessageHeldRoute
  '/webhook/email/message-link-clicked': typeof WebhookEmailMessageLinkClickedRoute
  '/webhook/email/message-loaded': typeof WebhookEmailMessageLoadedRoute
  '/webhook/email/message-sent': typeof WebhookEmailMessageSentRoute
  '/app/': typeof AppAppIndexRoute
  '/app/email/$thread_id': typeof AppAppEmailThread_idRouteWithChildren
  '/app/email/': typeof AppAppEmailIndexRoute
  '/app/settings/': typeof AppAppSettingsIndexRoute
  '/app/email/$thread_id/sender/$sender_id': typeof AppAppEmailThread_idSenderSender_idRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/signin': typeof AuthAuthSigninRoute
  '/auth/signup': typeof AuthAuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/graphql/$': typeof ApiGraphqlSplatRoute
  '/webhook/email/domain-dns-error': typeof WebhookEmailDomainDnsErrorRoute
  '/webhook/email/message-bounced': typeof WebhookEmailMessageBouncedRoute
  '/webhook/email/message-delayed': typeof WebhookEmailMessageDelayedRoute
  '/webhook/email/message-delivery-failed': typeof WebhookEmailMessageDeliveryFailedRoute
  '/webhook/email/message-held': typeof WebhookEmailMessageHeldRoute
  '/webhook/email/message-link-clicked': typeof WebhookEmailMessageLinkClickedRoute
  '/webhook/email/message-loaded': typeof WebhookEmailMessageLoadedRoute
  '/webhook/email/message-sent': typeof WebhookEmailMessageSentRoute
  '/app': typeof AppAppIndexRoute
  '/app/email/$thread_id': typeof AppAppEmailThread_idRouteWithChildren
  '/app/email': typeof AppAppEmailIndexRoute
  '/app/settings': typeof AppAppSettingsIndexRoute
  '/app/email/$thread_id/sender/$sender_id': typeof AppAppEmailThread_idSenderSender_idRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/app/email': typeof AppAppEmailRouteRouteWithChildren
  '/_auth/auth/signin': typeof AuthAuthSigninRoute
  '/_auth/auth/signup': typeof AuthAuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/graphql/$': typeof ApiGraphqlSplatRoute
  '/webhook/email/domain-dns-error': typeof WebhookEmailDomainDnsErrorRoute
  '/webhook/email/message-bounced': typeof WebhookEmailMessageBouncedRoute
  '/webhook/email/message-delayed': typeof WebhookEmailMessageDelayedRoute
  '/webhook/email/message-delivery-failed': typeof WebhookEmailMessageDeliveryFailedRoute
  '/webhook/email/message-held': typeof WebhookEmailMessageHeldRoute
  '/webhook/email/message-link-clicked': typeof WebhookEmailMessageLinkClickedRoute
  '/webhook/email/message-loaded': typeof WebhookEmailMessageLoadedRoute
  '/webhook/email/message-sent': typeof WebhookEmailMessageSentRoute
  '/_app/app/': typeof AppAppIndexRoute
  '/_app/app/email/$thread_id': typeof AppAppEmailThread_idRouteWithChildren
  '/_app/app/email/': typeof AppAppEmailIndexRoute
  '/_app/app/settings/': typeof AppAppSettingsIndexRoute
  '/_app/app/email/$thread_id/sender/$sender_id': typeof AppAppEmailThread_idSenderSender_idRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/email'
    | '/auth/signin'
    | '/auth/signup'
    | '/api/auth/$'
    | '/api/graphql/$'
    | '/webhook/email/domain-dns-error'
    | '/webhook/email/message-bounced'
    | '/webhook/email/message-delayed'
    | '/webhook/email/message-delivery-failed'
    | '/webhook/email/message-held'
    | '/webhook/email/message-link-clicked'
    | '/webhook/email/message-loaded'
    | '/webhook/email/message-sent'
    | '/app/'
    | '/app/email/$thread_id'
    | '/app/email/'
    | '/app/settings/'
    | '/app/email/$thread_id/sender/$sender_id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/signin'
    | '/auth/signup'
    | '/api/auth/$'
    | '/api/graphql/$'
    | '/webhook/email/domain-dns-error'
    | '/webhook/email/message-bounced'
    | '/webhook/email/message-delayed'
    | '/webhook/email/message-delivery-failed'
    | '/webhook/email/message-held'
    | '/webhook/email/message-link-clicked'
    | '/webhook/email/message-loaded'
    | '/webhook/email/message-sent'
    | '/app'
    | '/app/email/$thread_id'
    | '/app/email'
    | '/app/settings'
    | '/app/email/$thread_id/sender/$sender_id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/app/email'
    | '/_auth/auth/signin'
    | '/_auth/auth/signup'
    | '/api/auth/$'
    | '/api/graphql/$'
    | '/webhook/email/domain-dns-error'
    | '/webhook/email/message-bounced'
    | '/webhook/email/message-delayed'
    | '/webhook/email/message-delivery-failed'
    | '/webhook/email/message-held'
    | '/webhook/email/message-link-clicked'
    | '/webhook/email/message-loaded'
    | '/webhook/email/message-sent'
    | '/_app/app/'
    | '/_app/app/email/$thread_id'
    | '/_app/app/email/'
    | '/_app/app/settings/'
    | '/_app/app/email/$thread_id/sender/$sender_id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGraphqlSplatRoute: typeof ApiGraphqlSplatRoute
  WebhookEmailDomainDnsErrorRoute: typeof WebhookEmailDomainDnsErrorRoute
  WebhookEmailMessageBouncedRoute: typeof WebhookEmailMessageBouncedRoute
  WebhookEmailMessageDelayedRoute: typeof WebhookEmailMessageDelayedRoute
  WebhookEmailMessageDeliveryFailedRoute: typeof WebhookEmailMessageDeliveryFailedRoute
  WebhookEmailMessageHeldRoute: typeof WebhookEmailMessageHeldRoute
  WebhookEmailMessageLinkClickedRoute: typeof WebhookEmailMessageLinkClickedRoute
  WebhookEmailMessageLoadedRoute: typeof WebhookEmailMessageLoadedRoute
  WebhookEmailMessageSentRoute: typeof WebhookEmailMessageSentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app/': {
      id: '/_app/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/webhook/email/message-sent': {
      id: '/webhook/email/message-sent'
      path: '/webhook/email/message-sent'
      fullPath: '/webhook/email/message-sent'
      preLoaderRoute: typeof WebhookEmailMessageSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhook/email/message-loaded': {
      id: '/webhook/email/message-loaded'
      path: '/webhook/email/message-loaded'
      fullPath: '/webhook/email/message-loaded'
      preLoaderRoute: typeof WebhookEmailMessageLoadedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhook/email/message-link-clicked': {
      id: '/webhook/email/message-link-clicked'
      path: '/webhook/email/message-link-clicked'
      fullPath: '/webhook/email/message-link-clicked'
      preLoaderRoute: typeof WebhookEmailMessageLinkClickedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhook/email/message-held': {
      id: '/webhook/email/message-held'
      path: '/webhook/email/message-held'
      fullPath: '/webhook/email/message-held'
      preLoaderRoute: typeof WebhookEmailMessageHeldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhook/email/message-delivery-failed': {
      id: '/webhook/email/message-delivery-failed'
      path: '/webhook/email/message-delivery-failed'
      fullPath: '/webhook/email/message-delivery-failed'
      preLoaderRoute: typeof WebhookEmailMessageDeliveryFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhook/email/message-delayed': {
      id: '/webhook/email/message-delayed'
      path: '/webhook/email/message-delayed'
      fullPath: '/webhook/email/message-delayed'
      preLoaderRoute: typeof WebhookEmailMessageDelayedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhook/email/message-bounced': {
      id: '/webhook/email/message-bounced'
      path: '/webhook/email/message-bounced'
      fullPath: '/webhook/email/message-bounced'
      preLoaderRoute: typeof WebhookEmailMessageBouncedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhook/email/domain-dns-error': {
      id: '/webhook/email/domain-dns-error'
      path: '/webhook/email/domain-dns-error'
      fullPath: '/webhook/email/domain-dns-error'
      preLoaderRoute: typeof WebhookEmailDomainDnsErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graphql/$': {
      id: '/api/graphql/$'
      path: '/api/graphql/$'
      fullPath: '/api/graphql/$'
      preLoaderRoute: typeof ApiGraphqlSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/auth/signup': {
      id: '/_auth/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthAuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/auth/signin': {
      id: '/_auth/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthAuthSigninRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/app/email': {
      id: '/_app/app/email'
      path: '/app/email'
      fullPath: '/app/email'
      preLoaderRoute: typeof AppAppEmailRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/app/settings/': {
      id: '/_app/app/settings/'
      path: '/app/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppAppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/app/email/': {
      id: '/_app/app/email/'
      path: '/'
      fullPath: '/app/email/'
      preLoaderRoute: typeof AppAppEmailIndexRouteImport
      parentRoute: typeof AppAppEmailRouteRoute
    }
    '/_app/app/email/$thread_id': {
      id: '/_app/app/email/$thread_id'
      path: '/$thread_id'
      fullPath: '/app/email/$thread_id'
      preLoaderRoute: typeof AppAppEmailThread_idRouteImport
      parentRoute: typeof AppAppEmailRouteRoute
    }
    '/_app/app/email/$thread_id/sender/$sender_id': {
      id: '/_app/app/email/$thread_id/sender/$sender_id'
      path: '/sender/$sender_id'
      fullPath: '/app/email/$thread_id/sender/$sender_id'
      preLoaderRoute: typeof AppAppEmailThread_idSenderSender_idRouteImport
      parentRoute: typeof AppAppEmailThread_idRoute
    }
  }
}

interface AppAppEmailThread_idRouteChildren {
  AppAppEmailThread_idSenderSender_idRoute: typeof AppAppEmailThread_idSenderSender_idRoute
}

const AppAppEmailThread_idRouteChildren: AppAppEmailThread_idRouteChildren = {
  AppAppEmailThread_idSenderSender_idRoute:
    AppAppEmailThread_idSenderSender_idRoute,
}

const AppAppEmailThread_idRouteWithChildren =
  AppAppEmailThread_idRoute._addFileChildren(AppAppEmailThread_idRouteChildren)

interface AppAppEmailRouteRouteChildren {
  AppAppEmailThread_idRoute: typeof AppAppEmailThread_idRouteWithChildren
  AppAppEmailIndexRoute: typeof AppAppEmailIndexRoute
}

const AppAppEmailRouteRouteChildren: AppAppEmailRouteRouteChildren = {
  AppAppEmailThread_idRoute: AppAppEmailThread_idRouteWithChildren,
  AppAppEmailIndexRoute: AppAppEmailIndexRoute,
}

const AppAppEmailRouteRouteWithChildren =
  AppAppEmailRouteRoute._addFileChildren(AppAppEmailRouteRouteChildren)

interface AppRouteRouteChildren {
  AppAppEmailRouteRoute: typeof AppAppEmailRouteRouteWithChildren
  AppAppIndexRoute: typeof AppAppIndexRoute
  AppAppSettingsIndexRoute: typeof AppAppSettingsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAppEmailRouteRoute: AppAppEmailRouteRouteWithChildren,
  AppAppIndexRoute: AppAppIndexRoute,
  AppAppSettingsIndexRoute: AppAppSettingsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAuthSigninRoute: typeof AuthAuthSigninRoute
  AuthAuthSignupRoute: typeof AuthAuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAuthSigninRoute: AuthAuthSigninRoute,
  AuthAuthSignupRoute: AuthAuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGraphqlSplatRoute: ApiGraphqlSplatRoute,
  WebhookEmailDomainDnsErrorRoute: WebhookEmailDomainDnsErrorRoute,
  WebhookEmailMessageBouncedRoute: WebhookEmailMessageBouncedRoute,
  WebhookEmailMessageDelayedRoute: WebhookEmailMessageDelayedRoute,
  WebhookEmailMessageDeliveryFailedRoute:
    WebhookEmailMessageDeliveryFailedRoute,
  WebhookEmailMessageHeldRoute: WebhookEmailMessageHeldRoute,
  WebhookEmailMessageLinkClickedRoute: WebhookEmailMessageLinkClickedRoute,
  WebhookEmailMessageLoadedRoute: WebhookEmailMessageLoadedRoute,
  WebhookEmailMessageSentRoute: WebhookEmailMessageSentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
